parameters:
  ${{ if ne(variables['System.TeamProject'], 'public') }}:
    runAsPublic: false
  ${{ if eq(variables['System.TeamProject'], 'public') }}:
    runAsPublic: true
  foo: true

jobs:
  - ${{ if eq(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is true

  - ${{ if ne(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is false
