parameters:
  ${{ if and(ne(variables['System.TeamProject'], 'public', notIn(variables['Build.Reason'], 'PullRequest'))) }}:
    runAsPublic: false
  ${{ if or(eq(variables['System.TeamProject'], 'public', in(variables['Build.Reason'], 'PullRequest'))) }}:
    runAsPublic: true
  foo: true

jobs:
  - ${{ if eq(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is true

  - ${{ if ne(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is false
