parameters:
 jobName: ''


jobs:
- job: testWindows
  displayName: Hosted VS2017
  variables:
    _name: ${{ parameters['jobName'] }}
  pool:
    name: Hosted VS2017
  steps:
  - script: echo parameter name - %paramName%, variable name - %varName%
    env:
      paramName: ${{ parameters['jobName'] }}
      varName: $(_name)
