parameters:
  runAsPublic: false

jobs:
  - ${{ if eq(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is true

  - ${{ if ne(parameters.runAsPublic, true ) }}:
    - job: testWindows
      displayName: Hosted VS2017
      pool:
        name: Hosted VS2017
      steps:
      - script: echo runAsPublic is false
